function getDocs(req, res) {
  res.json({
    success: true,
    data: {
      name: 'PDF Generator SaaS API',
      version: '1.0.0',
      baseUrl: `${req.protocol}://${req.get('host')}`,
      headerFooterVariables: [
        {
          placeholder: '<span class="pageNumber"></span>',
          description: 'Current page number'
        },
        {
          placeholder: '<span class="totalPages"></span>',
          description: 'Total number of pages'
        },
        {
          placeholder: '<span class="date"></span>',
          description: 'Print date generated by Chromium'
        },
        {
          placeholder: '<span class="title"></span>',
          description: 'Document title'
        },
        {
          placeholder: '<span class="url"></span>',
          description: 'Document URL'
        }
      ],
      endpoints: [
        {
          method: 'GET',
          path: '/',
          description: 'Admin panel with HTML template editor',
          request: null,
          response: 'HTML page'
        },
        {
          method: 'POST',
          path: '/api/templates',
          description: 'Create a new HTML template',
          request: {
            name: 'string (required)',
            description: 'string (optional)',
            html_content: 'string (required)',
            css_content: 'string (optional)',
            sample_data: 'object or JSON string (optional)'
          },
          response: '{ success: true, data: { template }, error: "" }'
        },
        {
          method: 'GET',
          path: '/api/templates',
          description: 'List all templates',
          request: null,
          response: '{ success: true, data: [templates], error: "" }'
        },
        {
          method: 'GET',
          path: '/api/templates/:id',
          description: 'Get a single template by ID',
          request: null,
          response: '{ success: true, data: { template }, error: "" }'
        },
        {
          method: 'PUT',
          path: '/api/templates/:id',
          description: 'Update a template',
          request: {
            name: 'string (optional)',
            description: 'string (optional)',
            html_content: 'string (optional)',
            css_content: 'string (optional)',
            sample_data: 'object or JSON string (optional)'
          },
          response: '{ success: true, data: { template }, error: "" }'
        },
        {
          method: 'DELETE',
          path: '/api/templates/:id',
          description: 'Delete a template',
          request: null,
          response: '{ success: true, data: { deleted: true }, error: "" }'
        },
        {
          method: 'POST',
          path: '/api/generate-pdf',
          description: 'Generate a PDF and return as binary',
          request: {
            template_id: 'integer (required)',
            data: 'object (optional) - overrides sample_data',
            options: {
              pageSize: 'string (A4, Letter) default: A4',
              orientation: 'string (portrait, landscape) default: portrait',
              margin: { top: 'string', right: 'string', bottom: 'string', left: 'string' }
            }
          },
          response: 'PDF binary with Content-Type: application/pdf'
        },
        {
          method: 'POST',
          path: '/api/generate-pdf-file',
          description: 'Generate a PDF, save to disk, and return download URL',
          request: 'Same as /api/generate-pdf',
          response: '{ success: true, data: { download_url, filename }, error: "" }'
        },
        {
          method: 'GET',
          path: '/api/docs',
          description: 'This documentation',
          request: null,
          response: 'JSON API documentation'
        }
      ]
    },
    error: ''
  });
}

module.exports = { getDocs };
